// v-next-ts-graphql/src/components/next/routes/Episodes-id/BigEpisodeTile.svelte
<script lang="ts">

	import type { 
		PaginationBoardValue,
		PaginationItem
	} from '@tsLF/pages';
	import {
		LimitedViewOfItems
	} from '@tsLF/pages';

	import type { GT } from '@tsC/api-graphql-to-ex';


	import CharacterTile from '$comps/svelte/tileBoard/tiles/CharacterTile.svelte';
	import PaginationBoard from '$comps/svelte/pagination/PaginationBoard.svelte';




	export let data: GT.EpisodeFieldsFragment;


	let PaginationBoard__exit_value: PaginationItem;
	let PaginationBoard__entry_value: PaginationBoardValue;
	let currentViewCharacters: GT.CharacterPreviewFieldsFragment[] = [];


	const set_currentViewCharacters = (v: GT.CharacterPreviewFieldsFragment[]) => (currentViewCharacters = v);
	const set_PaginationBoard__entry_value = (v: PaginationBoardValue) => (PaginationBoard__entry_value = v);


	const viewCountOfCharacters = 40;

	let handleSelectedPage = (v: PaginationItem) => {};

	if(data.characters && data.characters.length > viewCountOfCharacters){
		const limitedViewOfCharacters = new LimitedViewOfItems(
			{
				viewCountOfItems: viewCountOfCharacters,
				set_limitedItems: set_currentViewCharacters,
				set_paginationBoard__entry_value: set_PaginationBoard__entry_value,
				thatArrayOfObjs: data.characters,
				buttonViewingLimit: 5
			}
		);
		
		handleSelectedPage = (v: PaginationItem) => (limitedViewOfCharacters.recievePaginationBoard__exit_value(v));

		limitedViewOfCharacters.init();
	}

	$:{
		if(PaginationBoard__exit_value){
			handleSelectedPage(PaginationBoard__exit_value);
		}
	}
</script>




<div
	class="
		bg-color--181a1b
		d-flex
		big-tile-box
	"
	style="
		height: 250px;
	"
> 
	<div
		class="
			big-tile-info-box
			d-flex
			fd-column
		"
		style="
			margin: 0 15px 5px 15px;
		"
	>
    <span
			class="
				big-tile-h
				tile-line
			"
    >
				Episode card
    </span>
		<span
			class="
				tile-line
			"
			style="
				border-bottom: solid 3px var(--colorPalette-b6b6b6);
				width: 100%;
			"
		></span>
    <span
			class="
				tile-line
				font-weight--normal
			"
    >
			Name:
	    <span
				class="
					color--f5f5f5
				"
	    >
				{ data.name }
	    </span>
    </span>

    <span 
			class="
				tile-line
				font-weight--normal
			"
		>
			Air date:
	    <span 
				class="
					color--f5f5f5
				"
			>
				{ data.air_date }
			</span>
    </span>

    <span 
			class="
				tile-line
				font-weight--normal
			"
		>
			Notation:
	    <span 
				class="
					color--f5f5f5
				"
			>
				{ data.episode }
			</span>
    </span>


    <span 
			class="
				tile-line
				font-weight--normal
			"
		>
			Count of characters who have been seen in the episode:
	    <span 
				class="
					color--f5f5f5
				"
			>
				{ data.characters.length }
			</span>
    </span>


	</div>
</div>
<div
	class="
		big-result-board
		w-100
	"
	style="
		margin-top: 10px;
		background-color: var(--colorPalette-181a1b);
	" 
>

	<div
		class="
			d-flex
			w-100
			jc-center
			bg-color--181a1b
		"
		style="
			margin-bottom: 10px;
		"
	>
		List of characters who have been seen in the episode.
	</div>

	{#if data.characters.length > viewCountOfCharacters}
		{#each currentViewCharacters as char, i (char.id) }
			{#if i === 0}
			<!-- 
				vot eto ebanoe gavnische tolko iz-za ebuchey uebischnoy svelte reactivity hueti
				kak je gorit s etogo ganvnischa
				rabotaet kogda kak, ebat' etu huynyu so vsemi razrabami v rot, chtobi vi suki v adu goreli mrazi
				poshli nahuy
			-->
				<div
					class="
						d-flex
						w-100
						jc-center
					"
					style="
						margin-bottom: 10px;
					"
				>
					<PaginationBoard 
						bind:entry_value={
							PaginationBoard__entry_value
						}
						bind:exit_value={
							PaginationBoard__exit_value
						}
					/>
				</div>
				<CharacterTile data={char} />
			{:else}
				<CharacterTile data={char} />
			{/if}
		{/each}
	{:else}
		{#each data.characters as char }
			<CharacterTile data={char} />
		{/each}
	{/if}

</div>

// v-next-ts-graphql/src/components/next/routes/Episodes-id/BigEpisodeTile.tsx
import { useState, useRef } from 'react';


import type { 
	PaginationBoardValue,
	PaginationItem
} from '@tsLF/pages';
import {
	LimitedViewOfItems
} from '@tsLF/pages';

import type { GT } from '@tsC/api-graphql-to-ex';


import CharacterTile from '@/components/next/tileBoard/tiles/CharacterTile';
import PaginationBoard from '@/components/next/pagination/PaginationBoard';




export default function BigEpisodeTile(
	{
		data
	}:{
		data: GT.EpisodeFieldsFragment;
	}
){
	const [PaginationBoard__entry_value, set_paginationBoard__entry_value] = useState<PaginationBoardValue>();
	const [currentViewCharacters, set_currentViewCharacters] = useState<GT.CharacterPreviewFieldsFragment[]>([]);
	const REF_limitedViewOfCharacters = useRef<LimitedViewOfItems>();
	const viewCountOfCharacters = 40;
	const [handleSelectedPage] = useState<(v: PaginationItem) => void>(
		()=>{
			let _handleSelectedPage = (_v: PaginationItem) => {};

			if(data.characters && data.characters.length > viewCountOfCharacters){
				const limitedViewOfCharacters = new LimitedViewOfItems(
					{
						viewCountOfItems: viewCountOfCharacters,
						set_limitedItems: set_currentViewCharacters,
						set_paginationBoard__entry_value,
						// prosti menya, gospod'... no ya greshen...
						// @ts-ignore-next-line
						thatArrayOfObjs: data.characters,
						buttonViewingLimit: 5
					}
				);

				REF_limitedViewOfCharacters.current = limitedViewOfCharacters;
				
				_handleSelectedPage = (v: PaginationItem) => 
				// prosti menya, gospod'... no ya greshen...
				// @ts-ignore-next-line
					REF_limitedViewOfCharacters.current.recievePaginationBoard__exit_value(v);


				limitedViewOfCharacters.init();
			}

			return _handleSelectedPage;
		}
	);

	const getPaginationBoard__exit_value = (v: PaginationItem | undefined) => {
		if(v){
			handleSelectedPage(v);
		}
	}

	return (
		<>
			<div
				className="
					bg-color--181a1b
					d-flex
					big-tile-box
				"
				style={{
					height: '250px'
				}}
			> 
				<div
					className="
						big-tile-info-box
						d-flex
						fd-column
					"
					style={{
						margin: '0 15px 5px 15px'
					}}
				>
			    <span
						className="
							big-tile-h
							tile-line
						"
			    >
							Episode card
			    </span>
					<span
						className="
							tile-line
						"
						style={{
							borderBottom: 'solid 3px var(--colorPalette-b6b6b6)',
							width: '100%'
						}}
					></span>
			    <span
						className="
							tile-line
							font-weight--normal
						"
			    >
						Name:
				    <span
							className="
								color--f5f5f5
							"
				    >
							{ data.name }
				    </span>
			    </span>
			
			    <span 
						className="
							tile-line
							font-weight--normal
						"
					>
						Air date:
				    <span 
							className="
								color--f5f5f5
							"
						>
							{ data.air_date }
						</span>
			    </span>
			
			    <span 
						className="
							tile-line
							font-weight--normal
						"
					>
						Notation:
				    <span 
							className="
								color--f5f5f5
							"
						>
							{ data.episode }
						</span>
			    </span>
			
			
			    <span 
						className="
							tile-line
							font-weight--normal
						"
					>
						Count of characters who have been seen in the episode:
				    <span 
							className="
								color--f5f5f5
							"
						>
							{ data.characters.length }
						</span>
			    </span>
			
			
				</div>
			</div>
			<div
				className="
					big-result-board
					w-100
				"
				style={{
					marginTop: '10px',
					backgroundColor: 'var(--colorPalette-181a1b)'
				}}
			>
			
				<div
					className="
						d-flex
						w-100
						jc-center
						bg-color--181a1b
					"
					style={{
						marginBottom: '10px'
					}}
				>
					List of characters who have been seen in the episode.
				</div>
		
				{
					(() =>{
						if(data.characters.length > viewCountOfCharacters){
							return (
								<div
									className="
										d-flex
										w-100
										jc-center
									"
									style={{
										marginBottom: '10px'
									}}
								>
									<PaginationBoard 
										// prosti menya, gospod'... no ya greshen...
										// @ts-ignore-next-line
										entry_value={
											PaginationBoard__entry_value
										}
										getExit_value={
											getPaginationBoard__exit_value
										}
										//vahui, blyat'!!!
										key={JSON.stringify(PaginationBoard__entry_value)}
									/>
								</div>
							);
						}
					})()
				}
					
				{
					(() => {
						const characterTiles = [];
						
						if(data.characters.length > viewCountOfCharacters){
							for(let i=0; i < currentViewCharacters.length; i++){
								characterTiles.push(
									<CharacterTile data={currentViewCharacters[i]} key={currentViewCharacters[i].id} />
								);

							}
						}else{
							for(let i = 0; i < data.characters.length; i++){
								characterTiles.push(
									// prosti menya, gospod'... no ya greshen...
									// @ts-ignore-next-line
									<CharacterTile data={data.characters[i]} key={data.characters[i].id} />
								);
							}
						}
						
						return characterTiles
					})()
				}
			
			</div>
		</>
	);
}
