// v-next-ts-graphql/src/app/episodes/page.tsx
'use client';
import { useState, useRef, useEffect } from 'react';


import { API_EPISODES__PATH } from '@tsCF/data';

import {
	TileBoard_SearchValue,
	NonTilesResultsForDrawingSearchPageTileBoard,
	pushStateByLegacy
} from '@tsLF/pages';

import { initEpisodesSearchPage	} from '@tsCF/pages';
  
import type { QueryParamCompatible_Base	} from '@tsLF/forURLSP';
import { getQPCBaseListFromURL	} from '@tsLF/forURLSP';

import type { GT } from '@tsC/api-graphql-to-ex';


import { useGlobalContext } from '@/components/context/globalContext';


import SearchItemNav from '@/components/next/routes/SearchItemNav';
import EpisodesSearch from '@/components/next/routes/Episodes/EpisodesSearch';
import TileBoard from '@/components/next/tileBoard/TileBoard';
import EpisodeTile from '@/components/next/tileBoard/tiles/EpisodeTile';
import TileBoard_Search from '@/components/next/tileBoard_Search/TileBoard_Search';




const pathName = API_EPISODES__PATH.name;

export default function Episodes(){

	const { 
		wUrql,
		wLocationChangeEventEmitter
	} = useGlobalContext();
	const [
		EpisodesSearch__update_values,
		set_EpisodesSearch__update_values
	] = useState<QueryParamCompatible_Base[]>([]); 
	const [
		TileBoard_SearchUpdateValue,
		set_TileBoard_SearchValue
	] = useState<TileBoard_SearchValue | undefined>(undefined);
	const [
		tiles,
		set_tiles
	] = useState<
		GT.EpisodePreviewFieldsFragment[]
		| NonTilesResultsForDrawingSearchPageTileBoard
	>('LOADING');
	const [
		get_EpisodesSearch__exit_values,
		setGet_EpisodesSearch__exit_values
	] = useState<(v: QueryParamCompatible_Base[]) => void>(() => (v: QueryParamCompatible_Base[]) => {});
	const [
		get_pagination__exit_value,
		setGet_pagination__exit_value
	] = useState<(v: number | undefined) => void>(() => (v: number | undefined) => {});


	const REF_initOutput = useRef();
	useEffect(
		() => {
			if(REF_initOutput.current){
				return;
			}

			REF_initOutput.current = initEpisodesSearchPage(				// prosti menya, gospod'... no ya greshen...
				{                                                     //@ts-ignore
					pathName,																						//@ts-ignore
					pushStateFn: pushStateByLegacy,											//@ts-ignore
					set_tiles,																					//@ts-ignore
					set_TileBoard_SearchValue,													//@ts-ignore
					set_EpisodesSearch__update_values,									//@ts-ignore
					wUrql,																							//@ts-ignore
					wLocationChangeEventEmitter
				}
			);

			const {
				handlePaginationSelection,
				handleEpisodesSearchApply,
				actionExecuterAfterMount,
				searchPageManager
			} = REF_initOutput.current;

			setGet_EpisodesSearch__exit_values(() => 
				(v: QueryParamCompatible_Base[]) => {
					// prosti menya, gospod'... no ya greshen...
					//@ts-ignore
					handleEpisodesSearchApply(v);
				}
			);
			setGet_pagination__exit_value(() => 
				(v: number | undefined) => {
					// prosti menya, gospod'... no ya greshen...
					//@ts-ignore
					handlePaginationSelection(v);
				}
			);

			// prosti menya, gospod'... no ya greshen...
			//@ts-ignore
			if(!actionExecuterAfterMount.isReady()){
				set_EpisodesSearch__update_values(
					getQPCBaseListFromURL(
						new URL(window.location.href)
					)
				);
				
				// prosti menya, gospod'... no ya greshen...
				//@ts-ignore
				actionExecuterAfterMount.setReady();
				
				// prosti menya, gospod'... no ya greshen...
				//@ts-ignore
				searchPageManager.init(EpisodesSearch__update_values);
			}
		}
		,[]
	);

	return (
		<>
			<SearchItemNav pathName={pathName}>
				<EpisodesSearch
					get_exitValue = {
						get_EpisodesSearch__exit_values
					}
					init_cachedValues = {
						EpisodesSearch__update_values
					}
					update_values = {
						EpisodesSearch__update_values
					}
				/>
			</SearchItemNav>

			{
				(
					() => {
				
						if (tiles === 'ERR') {
							return (
								<TileBoard>
									<p>Network Error. Try later or kill yourself. Thank you.</p>
								</TileBoard>
							);
						} else if(tiles === 'LOADING') {
							return (
								<TileBoard>
									<p>Loading...</p>
								</TileBoard>
							);
						} else if (tiles === 'NOT FOUND'){
							return (
								<TileBoard>
									<p>Nothing found.</p>
								</TileBoard>
							);
						}else if (Array.isArray(tiles)){
							let tileComponents = [];

							for(let i = 0; i < tiles.length; i++){
								tileComponents.push(
									<EpisodeTile data={tiles[i]} key={`${tiles[i].id} ${tiles[i].name}`} />
								);
							}

							if(!TileBoard_SearchUpdateValue){
								throw new Error('!TileBoard_SearchUpdateValue');
							}

							return (
								<TileBoard_Search
									update_value={
										TileBoard_SearchUpdateValue
									}
									getPagination__exit_value={
										get_pagination__exit_value
									}
								>
									{tileComponents}
								</TileBoard_Search>
							);
						}
			
					}
				)()
			}

		</>	
	);
}

// v-svelte-ts-graphql/src/routes/episodes/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	import { pushState } from '$app/navigation';


	import { API_EPISODES__PATH } from '@tsCF/data';

	import { capitalizeWord } from '@tsLF/pages';
	import type {
		TileBoard_SearchValue,
		NonTilesResultsForDrawingSearchPageTileBoard
	} from '@tsLF/pages';

	import { initEpisodesSearchPage	} from '@tsCF/pages';
	
	import type { QueryParamCompatible_Base	} from '@tsLF/forURLSP';
	import { getQPCBaseListFromURL	} from '@tsLF/forURLSP';

	import type { GT } from '@tsC/api-graphql-to-ex';


	import { APP_NAME } from '$comps/data';
	import g from '$comps/context/index.ts';
	const { 
		wUrql,
		wLocationChangeEventEmitter
	} = g();


	import SearchItemNav from '$comps/svelte/routes/SearchItemNav.svelte';
	import EpisodesSearch from '$comps/svelte/routes/Episodes/EpisodesSearch.svelte';
	import TileBoard from '$comps/svelte/tileBoard/TileBoard.svelte';
	import EpisodeTile from '$comps/svelte/tileBoard/tiles/EpisodeTile.svelte';
	import TileBoard_Search from '$comps/svelte/tileBoard_Search/TileBoard_Search.svelte';




	export let data;


	const pageTitle = capitalizeWord(API_EPISODES__PATH.name);
	const	pathName = data.psl.route.id.slice(1);


	let EpisodesSearch__exit_values: QueryParamCompatible_Base[] = [];
	let pagination__exit_value: number | undefined;


	let EpisodesSearch__update_values: QueryParamCompatible_Base[] = getQPCBaseListFromURL(new URL(data.psl.url));
	let TileBoard_SearchUpdateValue: TileBoard_SearchValue | undefined;
	let tiles: GT.EpisodePreviewFieldsFragment[] | NonTilesResultsForDrawingSearchPageTileBoard = 'LOADING';


	const set_EpisodesSearch__update_values = (v: QueryParamCompatible_Base[]) => (EpisodesSearch__update_values = v);
	const set_TileBoard_SearchValue = (v: TileBoard_SearchValue) => (TileBoard_SearchUpdateValue = v);
	const set_tiles = (v: GT.EpisodePreviewFieldsFragment[] | NonTilesResultsForDrawingSearchPageTileBoard) => (tiles = v);





	const {
		handlePaginationSelection,
		handleEpisodesSearchApply,
		actionExecuterAfterMount,
		searchPageManager
	} = initEpisodesSearchPage(
		{
			pathName,
			pushStateFn: pushState,
			set_tiles,
			set_TileBoard_SearchValue,
			set_EpisodesSearch__update_values,
			wUrql,
			wLocationChangeEventEmitter
		}
	);


	$:{
		tiles = tiles;
	}
	$:{
		handleEpisodesSearchApply(EpisodesSearch__exit_values);
	}
	$:{
		handlePaginationSelection(pagination__exit_value);
	}


	onMount(
		() => {
			actionExecuterAfterMount.setReady();
			
			searchPageManager.init(EpisodesSearch__update_values);
		}
	);

</script>




<svelte:head>
	<title>{ pageTitle } • { APP_NAME }</title>
	<meta name="description" content="{ APP_NAME } { pageTitle }" />
</svelte:head>


<SearchItemNav {pathName}>
	<EpisodesSearch
		bind:exit_values = {
			EpisodesSearch__exit_values
		}
		init_cachedValues = {
			EpisodesSearch__update_values
		}
		bind:update_values = {
			EpisodesSearch__update_values
		}
	/>
</SearchItemNav>


{#if tiles === 'ERR'}
	<TileBoard>
		<p>Network Error. Try later or kill yourself. Thank you.</p>
	</TileBoard>
{:else if tiles === 'LOADING'}
	<TileBoard>
		<p>Loading...</p>
	</TileBoard>
{:else if tiles === 'NOT FOUND'}
	<TileBoard>
		<p>Nothing found.</p>
	</TileBoard>
{:else if Array.isArray(tiles)}
	<TileBoard_Search
		bind:update_value={
			TileBoard_SearchUpdateValue
		}
		bind:pagination__exit_value={
			pagination__exit_value
		}
	>
	{#each tiles as tile }
		<EpisodeTile data={tile} />
	{/each}
	</TileBoard_Search>
{/if}
